# server port config
server:
  port:  8080

# db driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< .merge_file_a14964
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: MYSQL
    hikari:
      auto-commit: false
=======
    url: jdbc:mysql://localhost:3306/attraction_test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: bs7636511
>>>>>>> .merge_file_a02520

  # jpa config
  jpa:
<<<<<<< .merge_file_a14964
    generate-ddl: true
    hibernate:
      # ddl auto 설정: create - JPA가 DB와 상호작용시 기존의 스키마를 지우고 새로 생성, create-drop - JPA종료시점에서 기존에 있던 DB의 내용을 삭제
      #               update - JPA에 의해 변경된 부분만 반영, validate - entity와 table이 정상 매핑 되어있는지 확인, none - 초기화 동작 안함
      ddl-auto: update
=======
    generate-ddl: false
>>>>>>> .merge_file_a02520
    show-sql: true
    database: mysql
    properties:
      hibernate:
<<<<<<< .merge_file_a14964
=======
        ddl-auto: update
>>>>>>> .merge_file_a02520
        '[format_sql]': true

#jwt:
#  secret:
#    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

